- name: Install TFTPD server
  package:
    name: tftpd-hpa
    state: present

- name: Create TFTPD config
  template: src=tftpd-hpa.conf.j2 dest=/etc/default/tftpd-hpa
  register: tftpdconf

- name: Create a pxelinux directory if it does not exist
  file:
    path: /srv/tftp/pxelinux.cfg
    state: directory
    mode: '0755'

- name: Create /srv/tftp/pxelinux.cfg/default
  template: src=default-pxe.conf.j2 dest=/srv/tftp/pxelinux.cfg/default

- name: Create a preseed directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /srv/ftp/anonymous/isos/preseed
    - /srv/ftp/anonymous/isos/preseed/astra15
    - /srv/ftp/anonymous/isos/preseed/astra16

- name: Copy pxelinux.0
  copy:
    src: pxelinux.0
    dest: /srv/tftp
  register: pxelinuxconf

- name: Copy vesamenu.c32
  copy:
    src: vesamenu.c32
    dest: /srv/tftp

- name: Copy Astra15 image files
  copy:
    src: images/astra15/{{ item }}
    dest: /srv/tftp/images/astra15/
  with_items:
    - initrd.gz
    - linux
    - pxelinux.0

- name: Copy Astra16 image files
  copy:
    src: images/astra16/{{ item }}
    dest: /srv/tftp/images/astra16/
  with_items:
    - initrd.gz
    - linux
    - pxelinux.0

- name: Check TFTPD service status
  shell: /bin/netstat -tupln |  grep ":69" | sed -e 's/.*\///'
  register: portcheck
  changed_when: false

- name: Starting TFTPD service if not running
  service:
    name: tftpd-hpa
    state: started
  when: portcheck.stdout == ""

- name: Create configs
  template: src=preseed_{{ item[0] }}{{ item[1] }}.j2 dest=/srv/ftp/anonymous/isos/preseed/{{ item[0] }}/preseed_{{ item[0] }}{{ item[1] }}
  mode: '0644'
  with_nested:
    - [ "astra15", "astra16" ]
    - [ "_LVM.cfg", ".cfg" ]

- name: Restarting TFTPD service if running and config changed
  service:
    name: tftpd-hpa
    state: restarted
  when: (tftpdconf.changed and
        portcheck.stdout != "") or
        pxelinuxconf.changed
