- name: Install VSFTPD server
  package:
    name: vsftpd
    state: present

- name: Create VSFTPD config
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd.conf
  register: vsftpdconf

- name: Create VSFTPD directories
  file:
    path: "{{ item.directory }}"
    state: directory
    owner: ftp
    mode: "{{ item.mode }}"
  with_items:
    - { directory: "/srv/ftp/", mode: "555"}
    - { directory: "/srv/ftp/anonymous", mode: "555"}
    - { directory: "/srv/ftp/anonymous/Inbox", mode: "777"}

- name: Check VSFTPD service status
  stat:
    path: /var/run/vsftpd/vsftpd.pid
  register: vsftpdpid

- name: Starting VSFTPD service if not running
  service:
    name: vsftpd
    state: started
  when: vsftpdpid.stat.exists == False

- name: Restarting VSFTPD service if running and config changed
  service:
    name: vsftpd
    state: restarted
  when: vsftpdconf.changed and
        vsftpdpid.stat.exists == True
